version: '3.8'

#networks: this network create a new network . this network real name is kafka-net.
#other file can't use unless merged into same file.
#  kafka-connect-sample-net:
#    name: kafka-net
#    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kafka-net

  sftp:
    image: atmoz/sftp:alpine
    container_name: sftp-server
    platform: linux/amd64   # ✅ force compatibility with Intel-only image
    restart: unless-stopped
    ports:
      - "2222:22"
    command: sftpuser:sftppassword:::sink-output
    volumes:
       - ./sftp/upload:/data/spooldir/input
       - ./sftp/sink-output:/home/sftpuser/sink-output
    networks:
      - kafka-net

volumes:
  pgdata:
  #  Volume pgdata will store clean data.

  # Uncomment to enable local Elasticsearch
  # elasticsearch:
  #   image: elasticsearch:8.15.0
  #   container_name: elasticsearch
  #   restart: unless-stopped
  #   networks:
  #     - kafka-connect-sample-net
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     discovery.type: single-node
networks:
  kafka-net:
    external: true