/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.course.avro.data;
/** Sample enum */
@org.apache.avro.specific.AvroGenerated
public enum Avro04Enum implements org.apache.avro.generic.GenericEnumSymbol<Avro04Enum> {
  BLACK, BLUE, BROWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Avro04Enum\",\"namespace\":\"com.course.avro.data\",\"doc\":\"Sample enum\",\"symbols\":[\"BLACK\",\"BLUE\",\"BROWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
